routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DashboardController@index')->name('dashboard.index')->middleware('verified.message');
Route::get('/api/rates/{currency}', 'DashboardController@json_rates')->name('dashboard.json.rates');

Route::resource('/contribute', 'ContributeController')->only(['create', 'store'])->middleware('guest');

Route::prefix('profile')->name('profile.')->middleware('verified.message')->group(function () {
    Route::get('', 'ProfileController@index')->name('index');
    Route::post('/store', 'ProfileController@store')->name('store');

    Route::get('/password', 'PasswordController@index')->name('password.index');
    Route::post('/password/store', 'PasswordController@store')->name('password.store');
});

Route::prefix('kyc')->name('kyc.')->middleware('verified')->group(function () {
  Route::get('/', 'KycController@index')->name('index');
  Route::get('/status', 'KycController@status')->name('status');
});
Route::get('/kyc/callback', 'KycController@callback')->name('kyc.callback');

Auth::routes();
Route::post('/login', 'Auth\LoginController@authenticate')->name('login.auth');
Route::get('/email/verify/{token}', 'Auth\RegisterController@verify')->name('email.verification');

Route::prefix('payment')->name('payment.')->middleware('verified')->group(function () {
    Route::post('/', 'PaymentController@store')->name('store');
    Route::get('/success/{id}', 'PaymentController@success')->name('success');
    Route::get('/cancel/{id}', 'PaymentController@cancel')->name('cancel');
});
Route::post('/payment/callback', 'PaymentController@callbackNoHash')
    ->name('payment.callback_no_hash');

Route::post('/payment/callback/{hash}', 'PaymentController@callback')
    ->name('payment.callback');

Route::prefix('admin')->name('admin.')->middleware('admin')->group(function () {
    Route::get('/', 'Admin\AdminController@index')->name('index');
    Route::get('/transactions', 'Admin\TransactionController@index')->name('transactions.index');

    Route::prefix('users')->name('users.')->group(function () {
        Route::get('', 'Admin\UserController@index')->name('index');
        Route::get('/filter', 'Admin\UserController@filter')->name('filter');
        Route::get('/{user}/log', 'Admin\UserController@log')->name('log');
        Route::get('/{user}/transaction', 'Admin\UserController@transaction')->name('transaction');
        Route::post('/export', 'Admin\UserController@export')->name('export');
    });
});

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use CoinGate\CoinGate as Gateway;
use Carbon\Carbon;
use App\Currency;
use App\Order;
use App\Sale;

class DashboardController extends Controller
{
    private $meta;

    public function __construct()
    {
        $this->meta = [
            'min_buy_amount' => env('SWACE_MIN_BUY_AMOUNT'),
            'max_buy_amount' => env('SWACE_MAX_BUY_AMOUNT'),
            'token_pre_sale' => env('SWACE_PRESALE'),
            'token_price' => env('SWACE_TOKEN_PRICE'),
            'sale_amount' => env('SWACE_SALE_AMOUNT'),
            'bonus_percentage' => env('SWACE_BONUS_PERCENTAGE'),
            'coingate_fee' => env('SWACE_COINGATE_FEE'),
            'end_date' => env('SWACE_END_DATE'),
            'coingate_public_api' => env('COINGATE_PUBLIC_API'),
        ];
    }

    public function index()
    {
        $currencies = Currency::all();
        $verified = Auth::user()->isVerified();
        $tokens = Auth::user()->tokens();
        $email = Auth::user()->email;
        $orders = Order::where('user_id', Auth::user()->id)->orderBy('created_at', 'desc')->get();
        $token_end_date = Carbon::parse($this->meta['end_date'], Auth::user()->timezone);

        $days_left = $token_end_date->diffInDays(Carbon::now());
        $hours_left = $token_end_date->diffInHours(Carbon::now());
        $minutes_left = $token_end_date->diffInMinutes(Carbon::now());

        $collected = Sale::collectedAmount();
        $percentage = Sale::collectedPercentage($collected, $this->meta['sale_amount']);

        return view('dashboard/index', [
            'currencies' => $currencies,
            'verified' => $verified,
            'orders' => $orders,
            'collected' => $collected,
            'percentage' => $percentage,
            'tokens' => $tokens,
            'email' => $email,
            'token_end_date' => $token_end_date->toDayDateTimeString(),
            'days_left' => $days_left,
            'hours_left' => $hours_left,
            'minutes_left' => $minutes_left,
            'meta' => $this->meta
        ]);
    }

    public function json_rates(Request $request)
    {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $this->meta['coingate_public_api'] . 'USD/' . $request->currency);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $output = curl_exec($ch);
        curl_close($ch);

        echo $output;
    }
}

resources/views/dashboard/profile.blade.php
@extends('layouts.dashboard')

@section('head')
<title>Account settings | Swace</title>
@endsection

@section('content')
<main class="mb-5">
    <div class="canvas">
        <div class="bubble-1"></div>
        <div class="bubble-2"></div>
    </div>

    <div class="container ">

        <div class="row mt-3 mx-0">
            <div class="col-md-6 light-block p-4 p-sm-5 p-md-4 p-lg-5">
                <form class="form-signin" method="POST" action="{{ route('profile.store') }}" autocomplete="off">
                    @csrf

                    <div class="text-left muted-link">
                      <a class="btn-link d-inline-block" href="{{ route('dashboard.index') }}"> <i class="icon icon-arrow-left mr-1"></i> back to dashboard</a>
                    </div>

                    <div class="text-left mt-4 mb-3">
                        <h1 class="">Account settings</h1>
                    </div>

                    @component('components/business-form', ['personal' => $personal,
                                                            'company_name' => $company_name,
                                                            'company_code' => $company_code,
                                                            'company_vat' => $company_vat,
                                                            'company_address' => $company_address,
                                                            'company_city' => $company_city])

                    @endcomponent

                    <div class="row">
                        <div class="col-lg-6">
                            <input type="text" id="first_name" name="first_name" class="form-control my-2 py-3 px-3{{ $errors->has('first_name') ? ' is-invalid' : '' }}" placeholder="First name" value="{{ old('first_name', $first_name) }}" {{ $disabled }} required >

                            @if ($errors->has('first_name'))
                                <span class="invalid-feedback">
                                    <strong>{{ $errors->first('first_name') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="col-lg-6">
                            <input type="text" id="last_name" name="last_name" class="form-control  my-2 py-3 px-3{{ $errors->has('last_name') ? ' is-invalid' : '' }}" placeholder="Last name" value="{{ old('last_name', $last_name) }}" {{ $disabled }} required >

                            @if ($errors->has('last_name'))
                                <span class="invalid-feedback">
                                    <strong>{{ $errors->first('last_name') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group">
                      <?php echo $timezone->selectForm(old('timezone', $current_timezone), null, array('class' => 'form-control my-2 py-3 px-3', 'name' => 'timezone')) ?>
                    </div>

                    <div class="form-group">
                        <input type="email" id="email" class="form-control my-2 py-3 px-3{{ $errors->has('email') ? ' is-invalid' : '' }}" placeholder="E-mail address" value="{{ $email }}" disabled required >

                        @if ($errors->has('email'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('email') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <input type="text" id="mobile" class="form-control my-2 py-3 px-3{{ $errors->has('mobile') ? ' is-invalid' : '' }}" placeholder="Phone number" value="{{ $mobile }}" disabled >

                        @if ($errors->has('mobile'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('mobile') }}</strong>
                            </span>
                        @endif
                    </div>
                    <hr>
                    <h4 class="mt-4 mb-3">Change password</h4>
                    <div class="form-group">
                        <input type="password" id="password" name="password" class="form-control my-2 py-3 px-3{{ $errors->has('password') ? ' is-invalid' : '' }}" placeholder="New password" value="{{ old('password') }}">

                        @if ($errors->has('password'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('password') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <input type="password" id="password-confirm" name="password_confirmation" class="form-control my-2 py-3 px-3" placeholder="Confirm password" >

                    </div>

                    <button class="btn btn-primary btn-block text-uppercase mt-3 p-3 mb-4" type="submit">Save</button>

                </form>
            </div>

            <div class="col-md-6 text-center text-md-right">
                <div class="content">

                </div>
            </div>

        </div>
    </div>
</main>
@endsection