routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DashboardController@index')->name('dashboard.index')->middleware('verified.message');
Route::get('/api/rates/{currency}', 'DashboardController@json_rates')->name('dashboard.json.rates');

Route::resource('/contribute', 'ContributeController')->only(['create', 'store'])->middleware('guest');

Route::prefix('profile')->name('profile.')->middleware('verified.message')->group(function () {
    Route::get('', 'ProfileController@index')->name('index');
    Route::post('/store', 'ProfileController@store')->name('store');

    Route::get('/password', 'PasswordController@index')->name('password.index');
    Route::post('/password/store', 'PasswordController@store')->name('password.store');
});

Route::prefix('kyc')->name('kyc.')->middleware('verified')->group(function () {
  Route::get('/', 'KycController@index')->name('index');
  Route::get('/status', 'KycController@status')->name('status');
});
Route::get('/kyc/callback', 'KycController@callback')->name('kyc.callback');

Auth::routes();
Route::post('/login', 'Auth\LoginController@authenticate')->name('login.auth');
Route::get('/email/verify/{token}', 'Auth\RegisterController@verify')->name('email.verification');

Route::prefix('payment')->name('payment.')->middleware('verified')->group(function () {
    Route::post('/', 'PaymentController@store')->name('store');
    Route::get('/success/{id}', 'PaymentController@success')->name('success');
    Route::get('/cancel/{id}', 'PaymentController@cancel')->name('cancel');
});
Route::post('/payment/callback', 'PaymentController@callbackNoHash')
    ->name('payment.callback_no_hash');

Route::post('/payment/callback/{hash}', 'PaymentController@callback')
    ->name('payment.callback');

Route::prefix('admin')->name('admin.')->middleware('admin')->group(function () {
    Route::get('/', 'Admin\AdminController@index')->name('index');
    Route::get('/transactions', 'Admin\TransactionController@index')->name('transactions.index');

    Route::prefix('users')->name('users.')->group(function () {
        Route::get('', 'Admin\UserController@index')->name('index');
        Route::get('/filter', 'Admin\UserController@filter')->name('filter');
        Route::get('/{user}/log', 'Admin\UserController@log')->name('log');
        Route::get('/{user}/transaction', 'Admin\UserController@transaction')->name('transaction');
        Route::post('/export', 'Admin\UserController@export')->name('export');
    });
});

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{{ asset('images/favicon.ico') }}">
    <title>Swace</title>

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Admin') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <!--  Custom class to disabled the dashboard,
          not needed in front-end probably. -->
    <style media="screen">
        .disabled {
            opacity: 0.5;
            position: relative;
        }

        .disabled:after {
            width: 100%;
            height: 100%;
            display: block;
            content: "";
            position: absolute;
            left: 0;
            top: 0;
            cursor: not-allowed;
        }
    </style>

    @yield('head')

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ route('admin.index') }}">
                    Dashboard
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <li>
                            <a class="nav-link" href="{{ route('admin.users.index') }}">{{ __('User list') }}</a>
                        </li>
                        <li>
                            <a class="nav-link" href="{{ route('admin.transactions.index') }}">{{ __('Transactions') }}</a>
                        </li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <li>
                            <a class="nav-link" href="{{ route('logout') }}" onclick="event.preventDefault();
                                          document.getElementById('logout-form').submit();">{{ __('Log out') }}</a>
                              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                  @csrf
                              </form>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/dashboard.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="description" content="">
    <meta name="author" content="">
    <meta property="og:site_name" content="Swace" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Swace" />
    <meta property="og:image" content="{{ asset('/images/swacoin.svg') }}" />
    <meta property="og:description" content="Swace is a blockchain-based challenge platform where users gain rewards for engaging with brands" />
    <meta property="og:url" content="{{ url()->current() }}" />
    <link rel="icon" href="{{ asset('images/favicon.ico') }}">
    <title>Swace</title>

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-WNJ6KLX');</script>
    <!-- End Google Tag Manager -->

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">

    @yield('head')
</head>
<body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WNJ6KLX"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

    <nav class="navbar py-3 navbar-expand-sm navbar-dark">
        <div class="container">
            <a class="navbar-brand" href="{{ route('dashboard.index') }}">
                <img src="{{ asset('/images/swace-logo-color-white-type.svg') }}" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav my-4 my-sm-0 ml-auto ">
                    @guest
                    @else
                    <li class="nav-item mb-1 mb-sm-auto mr-sm-1 dropdown">
                        <a class="nav-link px-4 py-3 text-right dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ Auth::user()->email }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{{ route('profile.index') }}">Account settings</a>
                            @if(!auth()->user()->isKYC())
                            <a class="dropdown-item" href="{{ route('kyc.index') }}">KYC Verification</a>
                            @endif
                        </div>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link px-4 py-3 text-right text-uppercase"
                            href="{{ route('logout') }}"
                            onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                            {{ __('Sign out') }}
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')

    <footer>
      <div class="container">
            <div class="row">
                <div class="col-sm-6 order-md-1">
                    <div class="copyright text-center text-md-left mb-2 mb-md-5">Copyright 2016-2018</div>


                </div>
                <div class="col-sm-6 order-md-2">
                    <ul class="footer-nav text-center text-md-right p-0 mb-5">
                        <li><a href="https://www.swace.io/downloads/Token_Sale_TC_Swace.pdf" target="_blank">Terms &amp; Conditions</a></li>
                    </ul>
                </div>

            </div>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    @yield('footer')

</body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="description" content="">
    <meta name="author" content="">
    <meta property="og:site_name" content="Swace" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Swace" />
    <meta property="og:image" content="{{ asset('/images/swacoin.svg') }}" />
    <meta property="og:description" content="Swace is a blockchain-based challenge platform where users gain rewards for engaging with brands" />
    <meta property="og:url" content="{{ url()->current() }}" />
    <link rel="icon" href="{{ asset('images/favicon.ico') }}">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-WNJ6KLX');</script>
    <!-- End Google Tag Manager -->

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">

    @yield('head')
</head>
<body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WNJ6KLX"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

    @if(Session::has('message'))
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="alert {!! Session::get('type') == 'success' ? 'alert-success' : 'alert-danger' !!}" role="alert">
                    {{ Session::get("message") }}
                </div>
            </div>
        </div>
    </div>
    @endif

    <main class="">
        <div class="canvas">
            <div class="bubble-1"></div>
            <div class="shape-1"></div>
        </div>

        <div class="container">
            <div class="row mt-3 mx-0">
                <div class="col-md-6 light-block p-4 p-sm-5 p-md-4 p-lg-5">
                    @yield('content')
                </div>

                <div class="col-md-6 text-center text-md-right">
                    <div class="content">
                        @yield('menu')
                    </div>
                </div>

            </div>
        </div>
    </main>

    <footer>
        <div class="container">
            <div class="copyright text-center py-5">&copy; 2016-2018 Swace Ltd.</div>
        </div>
    </footer>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    @yield('footer')

</body>
</html>