routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DashboardController@index')->name('dashboard.index')->middleware('verified.message');
Route::get('/api/rates/{currency}', 'DashboardController@json_rates')->name('dashboard.json.rates');

Route::resource('/contribute', 'ContributeController')->only(['create', 'store'])->middleware('guest');

Route::prefix('profile')->name('profile.')->middleware('verified.message')->group(function () {
    Route::get('', 'ProfileController@index')->name('index');
    Route::post('/store', 'ProfileController@store')->name('store');

    Route::get('/password', 'PasswordController@index')->name('password.index');
    Route::post('/password/store', 'PasswordController@store')->name('password.store');
});

Route::prefix('kyc')->name('kyc.')->middleware('verified')->group(function () {
  Route::get('/', 'KycController@index')->name('index');
  Route::get('/status', 'KycController@status')->name('status');
});
Route::get('/kyc/callback', 'KycController@callback')->name('kyc.callback');

Auth::routes();
Route::post('/login', 'Auth\LoginController@authenticate')->name('login.auth');
Route::get('/email/verify/{token}', 'Auth\RegisterController@verify')->name('email.verification');

Route::prefix('payment')->name('payment.')->middleware('verified')->group(function () {
    Route::post('/', 'PaymentController@store')->name('store');
    Route::get('/success/{id}', 'PaymentController@success')->name('success');
    Route::get('/cancel/{id}', 'PaymentController@cancel')->name('cancel');
});
Route::post('/payment/callback', 'PaymentController@callbackNoHash')
    ->name('payment.callback_no_hash');

Route::post('/payment/callback/{hash}', 'PaymentController@callback')
    ->name('payment.callback');

Route::prefix('admin')->name('admin.')->middleware('admin')->group(function () {
    Route::get('/', 'Admin\AdminController@index')->name('index');
    Route::get('/transactions', 'Admin\TransactionController@index')->name('transactions.index');

    Route::prefix('users')->name('users.')->group(function () {
        Route::get('', 'Admin\UserController@index')->name('index');
        Route::get('/filter', 'Admin\UserController@filter')->name('filter');
        Route::get('/{user}/log', 'Admin\UserController@log')->name('log');
        Route::get('/{user}/transaction', 'Admin\UserController@transaction')->name('transaction');
        Route::post('/export', 'Admin\UserController@export')->name('export');
    });
});

app/User.php
<?php

namespace App;

use App\Notifications\MyResetPassword as ResetPasswordNotification;
use Carbon\Carbon;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    public $nice_date_format = 'F j, H:i a';

    public $precise_date_format = 'Y-m-d H:i:s';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'timezone', 'company_code', 'company_name', 'company_vat', 'personal', 'company_address', 'company_city', 'first_name', 'last_name', 'phone', 'email', 'password', 'email_token', 'verified', 'contributed', 'kyc', 'created_at'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'admin'
    ];

    public function isVerified(): bool
    {
        return $this->verified === 1 ? true : false;
    }

    public function isAdmin(): bool
    {
        return $this->admin === 1 ? true : false;
    }

    // Disable input if KYC is passed
    public function disableInput(): string
    {
        return $this->kyc === 1 ? 'disabled' : '';
    }

    public function isKYC(): bool
    {
        return $this->kyc === 1 ? true : false;
    }

    public function isCompany(): bool
    {
        return $this->personal === 1 ? false : true;
    }

    public function isContributed(): bool
    {
        return $this->contributed === 1 ? true : false;
    }

    public function verify()
    {
        $this->verified = 1;
        $this->email_token = null;
        $this->verified_at = date('Y-m-d H:i:s');
        $this->save();
    }

    public function tokens()
    {
        return Order::where('user_id', $this->id)->where('status_id', 4)->sum('tokens');
    }

    public function full_name()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function date_time(): string
    {
        return date('Y-m-d H:i:s');
    }

    public function format_date($date, string $type = 'nice'): string
    {
        $timestamp = strtotime($date);
        $nice = date($this->nice_date_format, $timestamp);
        $precise = date($this->precise_date_format, $timestamp);

        return ($type == 'nice') ? $nice : $precise;
    }

    public function registered_date(): string
    {
        return $this->format_date($this->created_at);
    }

    public function verified_date(string $type = 'nice'): string
    {
        return ($this->verified_at !== null) ? $this->format_date($this->verified_at, $type) : 'not verified';
    }

    public function last_online_date(string $type = 'nice'): string
    {
        $date = $this->logs()->orderBy('log_in', 'desc')->first();

        return ($date) ? $this->format_date($date->log_in, $type) : 'never';
    }

    public function count_purchase_amount(): float {

      return $this->with('orders')->findOrFail($this->id)
                                  ->orders()
                                  ->where('status_id', 3) // Paid
                                  ->sum('gross');

    }


    public function orders()
    {
        return $this->hasMany('App\Order', 'user_id', 'id');
    }


    public function logs()
    {
        return $this->hasMany('App\Log', 'user_id', 'id')->orderBy('log_in', 'desc');
    }

    public function addLogout(string $sessionId = null): void
    {
        $builder = $this->logs()->orderBy('log_in', 'desc');

        if (null !== $sessionId) {
            $builder->where('session_id', $sessionId);
        }

        $log = $builder->first();

        if ($log) {
            $log->log_out = Carbon::now();
            $log->save();
        }
    }

    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification(request()->ip(), $token, $this->email));
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Order;
use App\Flash;
use DB;

class UserController extends Controller
{
    private $filters;
    private $pagination;

    public function __construct()
    {
        $this->pagination = 10;
        $this->totalUsers = $this->countUsers();
        $this->filters = [
                            'contributed' => ['Not contributed', 'Contributed'],
                            'verified' => ['Un-verified','Verified'],
                        ];
    }

    private function countUsers(): int
    {
        $number = User::all()->count();

        return $number;
    }

    public function index()
    {
        $users = User::paginate($this->pagination);
        $formGET = '/?contributed=none&verified=none&amount_from=0&amount_to=0';

        return view('admin.user.index', [   'contributed' => -1,
                                            'verified' => -1,
                                            'amount_from' => null,
                                            'amount_to' => null,
                                            'filters' => $this->filters,
                                            'users' => $users,
                                            'total' => $this->totalUsers,
                                            'formGET' => $formGET]);
    }

    private function filter_amount(object $query, int $amount_from, int $amount_to) {


      if($amount_from !== 0 && $amount_to === 0) {
        /* If "from" is not 0, and "to" is 0, then do search from "from" to "infinity" */
        $amount_to = 99999999;
      } else if($amount_from === 0 && $amount_to === 0) {
        return false;
      }

      $query->select('users.id', DB::raw('SUM(gross) as total_amount'))
            ->from('orders')
            ->whereRaw('orders.user_id = users.id')
            ->whereRaw('status_id = 3') // Paid
            ->groupBy('users.id')
            ->havingRaw('total_amount >= ?', [$amount_from])
            ->havingRaw('total_amount <= ?', [$amount_to]);

    }

    public function filter(Request $request)
    {
        $contributed = $request->get('contributed');
        $verified = $request->get('verified');
        $amount_from = $request->get('amount_from');
        $amount_to = $request->get('amount_to');
        $formGET = '/?contributed=' . $contributed . '&verified=' . $verified . '&amount_from=' . $amount_from . '&amount_to=' . $amount_to;


        if ($contributed != 'none' && $verified != 'none') {
            $users = User::where('contributed', (int)$contributed)
                            ->where('verified', (int)$verified)
                            ->whereExists(function ($query) use ($amount_from, $amount_to){
                                  $this->filter_amount($query, (int)$amount_from, (int)$amount_to);
                            })
                            ->paginate($this->pagination);
            // dd($users);
        } elseif ($contributed != 'none') {
            $verified = -1;
            $users = User::where('contributed', (int)$contributed)
                            ->whereExists(function ($query) use ($amount_from, $amount_to){
                                  $this->filter_amount($query, (int)$amount_from, (int)$amount_to);
                            })
                            ->paginate($this->pagination);
        } elseif ($verified != 'none') {
            $contributed = -1;
            $users = User::where('verified', (int)$verified)
                            ->whereExists(function ($query) use ($amount_from, $amount_to){
                                  $this->filter_amount($query, (int)$amount_from, (int)$amount_to);
                            })
                            ->paginate($this->pagination);
        } else { // Both contributed and verified is none, redirect to index
            return redirect()->route('admin.users.index');
        }

        $users->appends(['contributed' => $contributed,
                         'verified' => $verified])->links();

        return view('admin.user.index', [   'contributed' => $contributed,
                                            'verified' => $verified,
                                            'amount_from' => $amount_from,
                                            'amount_to' => $amount_to,
                                            'filters' => $this->filters,
                                            'users' => $users,
                                            'total' => $this->totalUsers,
                                            'formGET' => $formGET]);
    }

    public function log(int $id)
    {
        $user = User::with('logs')->findOrFail($id);

        return view('admin.user.log', ['user' => $user]);
    }

    public function transaction(int $id)
    {
        $user = User::with('orders')->findOrFail($id);

        return view('admin.user.transaction', ['user' => $user ]);
    }

    public function export(Request $request)
    {
        $fields = [ 'id', 'first_name',
                    'last_name', 'phone',
                    'email', 'verified',
                    'contributed', 'created_at',
                    'verified_at'
                ];

        $request_users = $request->get('users');

        if ($request_users > 0) {
            $users = User::whereIn('id', $request_users)->get();
        } else {
            $contributed = $request->get('contributed');
            $verified = $request->get('verified');


            if ($contributed != 'none' && $verified != 'none') {
                $users = User::where('contributed', (int)$contributed)
                               ->where('verified', (int)$verified)
                               ->get();
            } elseif ($contributed != 'none') {
                $users = User::where('contributed', (int)$contributed)->get();
            } elseif ($verified != 'none') {
                $users = User::where('verified', (int)$verified)->get();
            } else {
                $users = User::all();
            }
        }

        $csv = new \Laracsv\Export();
        $csv->build($users, $fields);
        $csv->download();
    }
}

resources/views/admin/user/index.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-12">
            @if(Session::has('message'))
            <div class="alert {!! Session::get('type') == 'success' ? 'alert-success' : 'alert-danger' !!}" role="alert">
                {{ Session::get("message") }}
            </div>
            @endif
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-md-4">
            <h1>
                <input type="submit" class="btn btn-success" value="Export" form="export">
                User List ({{ $total }})
            </h1>
        </div>
        <div class="col-md-8">
            @component('admin/components/user-filters', ['contributed' => $contributed,
                                                        'verified' => $verified,
                                                        'filters' => $filters,
                                                        'amount_to' => $amount_to,
                                                        'amount_from' => $amount_from])
            @endcomponent
        </div>
        <div class="col-md-12 mt-3">
            <form id="export" action="{{ route('admin.users.export') . $formGET}}" method="POST">
                @csrf

                <table class="table">
                  <thead class="thead-light">
                    <tr>
                      <th scope="col">
                          <input id="select_all" type="checkbox">
                      </th>
                      <th scope="col">#</th>
                      <th scope="col">Full name</th>
                      <th scope="col">E-mail</th>
                      <th scope="col">Phone</th>
                      <th scope="col">Dates</th>
                      <th scope="col">Amount</th>
                      <th scope="col">Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    @if(count($users) > 0)
                        @foreach($users as $user)
                        <?php $amount = $user->count_purchase_amount(); ?>

                        <tr class="@if($amount >= 15000) table-warning @endif">
                            <td>
                                <input type="checkbox" class="checkbox" name="users[]" value="{{ $user->id }}">
                            </td>
                          <th scope="row">
                              {{ $user->id }}
                          </th>
                          <td>{{ $user->full_name() }}</td>
                          <td>
                              {{ $user->email }}
                              <span class="badge badge-{{ ($user->verified) ? 'success' : 'danger' }}">{{ ($user->verified) ? 'verified' : 'non-verified' }}</span>
                              <span class="badge badge-{{ ($user->contributed) ? 'success' : 'danger' }}">{{ ($user->contributed) ? 'contributed' : 'not contributed' }}</span>
                          </td>
                          <td>{{ $user->phone }}</td>
                          <td>
                             <p class="mb-1">
                                 Registered at: <span title='{{ $user->format_date($user->created_at, "precise") }}'>{{ $user->format_date($user->created_at) }}</span>

                             </p>
                             <p class="mb-1">
                                 Verified at: <span title='{{ $user->verified_date("precise") }}'>{{ $user->verified_date() }}</span>

                             </p>
                             <p class="mb-1">
                                 Last online at: <span title='{{ $user->last_online_date("precise") }}'>{{ $user->last_online_date() }}</span>

                             </p>
                          </td>
                          <td>
                            {{ number_format($amount, 2) }} $
                          </td>
                          <td>
                             <p><a href="{{ route('admin.users.transaction', $user->id) }}" class="btn btn-success btn-sm">Transactions</a></p>
                             <p><a href="{{ route('admin.users.log', $user->id) }}" class="btn btn-primary btn-sm">IP log</a></p>
                          </td>
                        </tr>

                        @endforeach
                    @else:
                    <tr>
                        <td colspan="11">
                            No users yet.
                        </td>
                    </tr>
                    @endif
                  </tbody>
                </table>
            </form>

            {{ $users->links() }}

            <script type="text/javascript">

                document.addEventListener('DOMContentLoaded', function() {

                    let form = document.querySelector('#export'),
                        checkboxes = null;

                    form.querySelector('#select_all').addEventListener('change', function() {

                        checkboxes = form.querySelectorAll('.checkbox');

                        if(this.checked) {
                            for(i = 0; i < checkboxes.length; i++) {
                                checkboxes[i].checked = true;
                            }
                        }
                        else {
                            for(i = 0; i < checkboxes.length; i++) {
                                checkboxes[i].checked = false;
                            }
                        }

                    });

                })
            </script>
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/log.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

    <div class="row mt-5">
        <h1 class="mr-auto">IP address log of <strong>{{ $user->full_name() }}</strong> (#{{ $user->id }})</h1>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12">
                    <a href="{{ URL::previous() }}" class="float-right btn btn-danger btn-lg">Back</a>
                </div>
            </div>
        </div>
        <div class="col-md-12 mt-3">
            <table class="table">
              <thead class="thead-light">
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">IP Address</th>
                  <th scope="col">Log in</th>
                  <th scope="col">Log out</th>
                  <th scope="col">Online time</th>
                </tr>
              </thead>
              <tbody>
                @if(count($user->logs) > 0)
                    @foreach($user->logs as $log)
                    <tr>
                      <th scope="row">
                          {{ $log->id }}
                      </th>
                      <td>{{ $log->ip_address }}</td>
                      <td>{{ $log->log_in }}</td>
                      <td>{{ $log->log_out }}</td>
                      <td>{{ $log->onlineTime() }}</td>
                    </tr>
                    @endforeach
                @else:
                <tr>
                    <td colspan="11">
                        User ip address log is empty.
                    </td>
                </tr>
                @endif
              </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/transaction.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">

    <div class="row mt-5">
      <div class="mr-auto">
        <h1 class="mr-auto">Transaction history of <strong>{{ $user->full_name() }}</strong> (#{{ $user->id }})</h1>
        <ul>
          <li>Type: @if($user->personal) Personal @else Company @endif</li>
          @if($user->company_name)<li>Company Name: {{ $user->company_name }}</li> @endif
          @if($user->company_code)<li>Company Code: {{ $user->company_code }}</li> @endif
          @if($user->company_vat)<li>Company VAT: {{ $user->company_vat }}</li> @endif
          @if($user->company_address)<li>Company Address: {{ $user->company_address }}</li>@endif
        </ul>
      </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12">
                    <a href="{{ URL::previous() }}" class="float-right btn btn-danger btn-lg">Back</a>
                </div>
            </div>
        </div>
        <div class="col-md-12 mt-3">
            @component('admin/components/transaction-user', ['orders' => $user->orders])
            @endcomponent
        </div>
    </div>
</div>
@endsection