routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DashboardController@index')->name('dashboard.index')->middleware('verified.message');
Route::get('/api/rates/{currency}', 'DashboardController@json_rates')->name('dashboard.json.rates');

Route::resource('/contribute', 'ContributeController')->only(['create', 'store'])->middleware('guest');

Route::prefix('profile')->name('profile.')->middleware('verified.message')->group(function () {
    Route::get('', 'ProfileController@index')->name('index');
    Route::post('/store', 'ProfileController@store')->name('store');

    Route::get('/password', 'PasswordController@index')->name('password.index');
    Route::post('/password/store', 'PasswordController@store')->name('password.store');
});

Route::prefix('kyc')->name('kyc.')->middleware('verified')->group(function () {
  Route::get('/', 'KycController@index')->name('index');
  Route::get('/status', 'KycController@status')->name('status');
});
Route::get('/kyc/callback', 'KycController@callback')->name('kyc.callback');

Auth::routes();
Route::post('/login', 'Auth\LoginController@authenticate')->name('login.auth');
Route::get('/email/verify/{token}', 'Auth\RegisterController@verify')->name('email.verification');

Route::prefix('payment')->name('payment.')->middleware('verified')->group(function () {
    Route::post('/', 'PaymentController@store')->name('store');
    Route::get('/success/{id}', 'PaymentController@success')->name('success');
    Route::get('/cancel/{id}', 'PaymentController@cancel')->name('cancel');
});
Route::post('/payment/callback', 'PaymentController@callbackNoHash')
    ->name('payment.callback_no_hash');

Route::post('/payment/callback/{hash}', 'PaymentController@callback')
    ->name('payment.callback');

Route::prefix('admin')->name('admin.')->middleware('admin')->group(function () {
    Route::get('/', 'Admin\AdminController@index')->name('index');
    Route::get('/transactions', 'Admin\TransactionController@index')->name('transactions.index');

    Route::prefix('users')->name('users.')->group(function () {
        Route::get('', 'Admin\UserController@index')->name('index');
        Route::get('/filter', 'Admin\UserController@filter')->name('filter');
        Route::get('/{user}/log', 'Admin\UserController@log')->name('log');
        Route::get('/{user}/transaction', 'Admin\UserController@transaction')->name('transaction');
        Route::post('/export', 'Admin\UserController@export')->name('export');
    });
});

resources/views/admin/components/transaction-user.blade.php
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Date</th>
      <th scope="col">Amount</th>
      <th scope="col">Rate</th>
      <th scope="col">Gross</th>
      <th scope="col">Fee</th>
      <th scope="col">Net</th>
      <th scope="col">Tokens</th>
      <th scope="col">Bonus</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
    @if(count($orders) > 0)
        @foreach($orders as $order)
        <tr>
          <th scope="row">
              {{ $order->id }}
          </th>
          <td>{{ $order->created_at->format('Y-m-d H:i') }}</td>
          <td>{{ $order->amount }} {{ strtoupper($order->type->short_title) }}</td>
          <td>{{ $order->rate }} $</td>
          <td>{{ $order->gross }} $</td>
          <td>{{ $order->fee }} $</td>
          <td>{{ ($order->net) ? $order->net.' $' : '' }}</td>
          <td>{{ $order->tokens }}</td>
          <td>{{ $order->bonus }}</td>
          <td>
              <p>
                  <a href="{{ $order->invoice }}">Invoice</a>
              </p>
              <span class="badge{{ $order->status->class() }}">{{ $order->status->title }}</span>
          </td>
        </tr>
        @endforeach
    @else:
    <tr>
        <td colspan="11">
            Your transaction history is empty.
        </td>
    </tr>
    @endif
  </tbody>
</table>

resources/views/admin/components/transaction-users.blade.php
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Full name</th>
      <th scope="col">Email</th>
      <th scope="col">Date</th>
      <th scope="col">Amount</th>
      <th scope="col">Rate</th>
      <th scope="col">Gross</th>
      <th scope="col">Fee</th>
      <th scope="col">Net</th>
      <th scope="col">Tokens</th>
      <th scope="col">Bonus</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
    @if(count($orders) > 0)
        @foreach($orders as $order)
        <tr>
          <th scope="row">
              {{ $order->id }}
          </th>
          <td>{{ $order->user->full_name() }}</td>
          <td>{{ $order->user->email }}</td>
          <td>{{ $order->created_at->format('Y-m-d H:i') }}</td>
          <td>{{ $order->amount }} {{ strtoupper($order->type->short_title) }}</td>
          <td>{{ $order->rate }} $</td>
          <td>{{ $order->gross }} $</td>
          <td>{{ $order->fee }} $</td>
          <td>{{ ($order->net) ? $order->net.' $' : '' }}</td>
          <td>{{ $order->tokens }}</td>
          <td>{{ $order->bonus }}</td>
          <td>
              <p>
                  <a href="{{ $order->invoice }}">Invoice</a>
              </p>
              <span class="badge{{ $order->status->class() }}">{{ $order->status->title }}</span>
          </td>
        </tr>
        @endforeach
    @else:
    <tr>
        <td colspan="11">
            Your transaction history is empty.
        </td>
    </tr>
    @endif
  </tbody>
</table>

resources/views/admin/components/user-filters.blade.php
<form action="{{ route('admin.users.filter') }}" method="GET" class="form-inline">
  <div class="form-group mb-2">
    <label for="contributed">Filters: </label>

    <select id="contributed" class="form-control ml-3" name="contributed">
        <option value='none' selected>Choose...</option>
        @foreach($filters['contributed'] as $option)
        <option value="{{ $loop->index }}" {{ ($loop->index == $contributed) ? 'selected' : '' }}>{{ $option }}</option>
        @endforeach
    </select>
  </div>
  <div class="form-group mx-sm-2 mb-2">
      <select id="verified" class="form-control" name="verified">
          <option value='none' selected>Choose...</option>
          @foreach($filters['verified'] as $option)
          <option value="{{ $loop->index }}" {{ ($loop->index == $verified) ? 'selected' : '' }}>{{ $option }}</option>
          @endforeach
      </select>
  </div>
  <div class="form-group mx-sm-2 mb-2">
      <input type="number" class="form-control" name="amount_from" value="{{ old('amount_from', $amount_from) }}" placeholder="0" style="max-width:100px">
  </div>
  <div class="form-group mx-sm-2 mb-2">
      <input type="number" class="form-control" name="amount_to" value="{{ old('amount_to', $amount_to) }}" placeholder="10000" style="max-width:100px">
  </div>
  <button type="submit" class="btn btn-primary mb-2">Filter</button>
  <a href="{{ route('admin.users.index') }}" class="btn btn-danger mb-2 ml-3">Reset</a>
</form>